'''

Quero ver a possibilidade de criar um programa usando o Python para automatizar enviando os dados da planilha para preencher os campos mutáveis no certificado padrão.

Tipo nome do curso, nome participante, tipo de participação, data do inicio, data do final, carga horária, data da emissão do certificado e as assinaturas do Gestor Geral, do Coordenador e do aluno.

Pegar dados(texto) -> sobrepor de uma imagem(certificado padrão)

# Pegar os dados da planilha
Tais como nome do curso, nome participante, tipo de participação, data do inicio, data do final, carga horária, data da emissão do certificado

# Tranferir para a imagem do certificado

I want to see the possibility of creating a program using Python to automate sending spreadsheet data to populate the changeable fields in the default certificate.

Like course name, participant name, type of participation, start date, end date, workload, certificate issuance date and the signatures of the General Manager, the Coordinator and the student.

Get data (text) -> overlay from an image (standard certificate)

#Get the data from the spreadsheet
Type course name, participant name, type of participation, start date, end date, workload, certificate issuance date

# Transfer to certificate image

'''

# Pegar os dados da planilha #Get the data from the spreadsheet

# Get the data from the spreadsheet
# Importar bibliotecas usadas para rodar o codigo openpyxl(import openpyxl) para abrir o arquivo excel e o pillow (from PIL import Image, ImageDraw, ImageFont) para abrir a imagem do certificado 
# Import libraries used to run the code openpyxl(import openpyxl) to open the excel file and the pillow(from PIL import Image, ImageDraw, ImageFont) to open the certificate image
import openpyxl
from PIL import Image, ImageDraw, ImageFont

# Criar as variaveis para abrir a planilha e a aba da planilha 
# Create the variables to open the spreadsheet and the spreadsheet tab
workbookStudents = openpyxl.load_workbook('planilha_alunos.xlsx')
sheetStudents = workbookStudents['Sheet1']

# Colocar um indice para cada linha da planilha e colocar um liite minimo e maximo para gerar os certificados durante o periodo de teste 
# Put an index for each row of the spreadsheet and put a minimum and maximum limit to generate the certificates during the test period
for index, line in enumerate(sheetStudents.iter_rows(min_row = 2)):

    # Criar a célula que contém a info que é preciso para encontrar a linha correta dos requisitos do certificado 
    # Create the cell that contains the info that is needed to find the correct line of the certificate requirements
    courseName = line[0].value # Nome do curso # Course name
    participantName = line[1].value # Nome do participante # Participant name
    typeParticipation = line[2].value # Tipo de participação # Type of participation
    startDate = line[3].value # Data do inicio # Start date
    endDate = line[4].value # Data do final # End date
    workload = line[5].value # Carga horária # Workload
    certificateIssuanceDate = line[6].value # Data da emissão do certificado # Certificate issuance date

    # Tranferir os dados da planilha para a imagem do certificado
    # Transfer the data from the spreadsheet to the certificate image
    # Definindo fonte a ser usada 
    # Defining font to be used
    fontName = ImageFont.truetype('./tahomabd.ttf', 90)
    generalFont = ImageFont.truetype('./tahoma.ttf', 80)
    dataFont = ImageFont.truetype('./tahoma.ttf', 55)

    # Crie o caminho para abrir a imagem do certificado 
    # Create the path to open the certificate image
    image = Image.open('./certificado_padrao.jpg')
    draw = ImageDraw.Draw(image)

    # Adicione as informações ao camposrespectivos no certificado 
    # Adding the information to the respective fields in the certificate
    draw.text((1020, 827), participantName, fill = 'black', font=fontName)
    draw.text((1060, 950), courseName, fill = 'black', font = generalFont)
    draw.text((1435, 1065), typeParticipation, fill = 'black', font=generalFont)

    # Para o programa ler datas e carga horária, é preciso mudar a class de número para string 
    # For the program to read dates and workload, you need to change the number class to string
    draw.text((1480, 1190), str(workload), fill = 'black', font = generalFont)

    # Assim é feito com a data de inicio e de termino 
    # This is done with the start and end date
    draw.text((750, 1770), str(startDate), fill = 'blue', font = dataFont)
    draw.text((750, 1930), str(endDate), fill = 'blue', font = dataFont)
    
    draw.text((2220, 1930), certificateIssuanceDate, fill = 'blue', font = dataFont)
    

    # Criar uma pasta para guardar as imagens geradas pelo bot para melhor organização. 
    # Create a folder to save the images generated by the bot for better organization.
    # Rodar o codigo para gerar o primeiro certificado 
    # Run the code to generate the first certificate
    image.save(f'./certificate_img/ {index} {participantName} certificate.png')