"""
Passo a Passo

- 1° Pegar os dados da planilha.

- 2º Importar bibliotecas usadas para rodar o codigo openpyxl(import openpyxl) para abrir o arquivo excel e o pillow (from PIL import Image, ImageDraw, ImageFont) para abrir a imagem do certificado.

- 3° Criar as variaveis para abrir a planilha e a aba da planilha.

- 4° Colocar um indice para cada linha da planilha e colocar um liite minimo e maximo para gerar os certificados durante o periodo de teste.

- 5° Criar a célula que contém a info que é preciso para encontrar a linha correta dos requisitos do certificado.

- 6° e 7° Tranferir os dados da planilha para a imagem do certificado. Definindo fonte a ser usada. Definindo fonte a ser usada.

- 8º Crie o caminho para abrir a imagem do certificado.

- 9° Adicione as informações ao camposrespectivos no certificado.

- 10° Para o programa ler datas e carga horária, é preciso mudar a class de número para string.

- 11° Assim é feito com a data de inicio e de termino.

- 12° Criar uma pasta para guardar as imagens geradas pelo bot para melhor organização. 

- 13º Rodar o codigo para gerar o primeiro certificado.


"""
"""
Steps

- 1° Get the data from the spreadsheet.

- 2º Import libraries used to run the code openpyxl(import openpyxl) to open the excel file and the pillow(from PIL import Image, ImageDraw, ImageFont) to open the certificate image.

- 3° Create the variables to open the spreadsheet and the spreadsheet tab.

- 4° Put an index for each row of the spreadsheet and put a minimum and maximum limit to generate the certificates during the test period.

- 5° Create the cell that contains the info that is needed to find the correct line of the certificate requirements.

- 6° and 7° Transfer the data from the spreadsheet to the certificate image. Defining font to be used.

- 8º Create the path to open the certificate image.

- 9° Adding the information to the respective fields in the certificate.

- 10° For the program to read dates and workload, you need to change the number class to string.

- 11° The same need to be done with the start and end date.

- 12° and  Create a folder to save the images generated by the bot for better organization. 

- 13° Run the code to generate the first certificate.

"""